# System clipboard
hook global RegisterModified '"' %{ nop %sh{
  printf %s "$kak_main_reg_dquote" | xclip -in -selection clipboard >&- 2>&-
} }

map global user p -docstring 'Paste (After)' '<a-!>xclip -out -selection clipboard<ret>'
map global user P -docstring 'Paste (Before)' '!xclip -out -selection clipboard<ret>'
map global user R -docstring 'Replace' '|xclip -out -selection clipboard<ret>'

# Tools
define-command open -params ..1 -docstring "open a file" %{
  prompt -shell-script-candidates "fd --type file . %arg{1}" "open: " %{
    edit %val{text}
  }
}

define-command bc -docstring "simple math with bc" %{
  prompt -init %val{selection} "bc: " %{
    set-register '"' %sh{ echo "scale=3; $kak_text" | bc -l -q }
    echo %reg{"}
  }
}

# Options
set-option global indentwidth 2
set-option global tabstop %opt{indentwidth}
set-option global aligntab false
set-option global scrolloff 2,0

# Keys
map global insert <tab> '<a-;><a-gt>'
map global insert <s-tab> '<a-;><a-lt>'

map -docstring "toggle line comment" global user c ': comment-line<ret>'
map -docstring "toggle block comment" global user C ': comment-block<ret>'
map -docstring "open a file" global user f ': open<ret>'
map -docstring "open a file near current" global user F ': open %sh{ dirname $kak_buffile }<ret>'
map -docstring "simple math with bc" global user = ': bc<ret>'

# Appearance
colorscheme tomorrow-night
set-option global scrolloff 2,0
set-option -add global ui_options terminal_assistant=none
add-highlighter global/ number-lines

# Editing
auto-pairs-enable

# File types
hook global WinSetOption filetype=markdown %{
  set-option window autowrap_column 80
  autowrap-enable
}
